export const SERVICE_PENDING = "SERVICE_PENDING"
export const SERVICE_SUCCESS_RESPONSE = "SERVICE_SUCCESS_RESPONSE";
export const SERVICE_FAIL_RESPONSE = "SERVICE_FAIL_RESPONSE";
export const SERVICE_ERROR = "SERVICE_ERROR";
export const SHOW_REGISTRATION_SUCCESS = "SHOW_REGISTRATION_SUCCESS";
export const HIDE_ALERT = "HIDE_ALERT";